### PR TITLE
Optimize the icon loading logic for faster rendering

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Don't run the icon loading logic when loading the landing page
- Load the icons after the first render of the iconography page
- Convert the metadata arrays into objects for faster search/indexing

### CODE REVIEW

**Comment by jeffvg** [comment]
locally landing page loading up pretty fast. Up to 56% on performance. 2.7s on index loaded

**Review by huayunh — APPROVED** [review]
page spins way faster

**Comment by huayunh** [comment]
Merging to test mobile performance

**Comment by huayunh** [comment]
Looks like apple's website is temporarily down.

**Pull request merged**
