### PR TITLE
Update MUI meta data

### PR DESCRIPTION
**Pull request by huayunh**
Fixes PXBLUE-???

#### Changes proposed in this Pull Request:
- Updated Material Icon meta data to latest
- I guess MUI hasn't pulled latest Material Icons down yet. Not all icons are searchable. Projects spin up fine.

After icons-mui package gets published we can make another PR to make sure PX Blue icons get shown through

### CODE REVIEW

**Review by joebochill — COMMENTED** [review]
So what all is actually included in here? I noticed that most of the icons I was anticipating aren't going to be released until @material-ui/icons@5.0.0

**Review by joebochill — APPROVED** [review]

**Comment by huayunh** [comment]
Story to upgrade everything to MUI v5 created

**Comment by joebochill** [comment]
I just checked and the line count in the new meta file and the old meta file are the same. I suspect we were already up to date?

**Comment by huayunh** [comment]
>  the line count in the new meta file and the old meta file are the same. 

dev:
image

This branch:
image

**Comment by joebochill** [comment]
I suppose it would help if I had checked out the correct branch 🤦

**Comment by joebochill** [comment]
So does this mean that Material has doubled their number of icons?!

**Pull request merged**
