### PR TITLE
Add app bar to patterns

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Add R, Ng, RN collapsible appbar related things to design patterns

### CODE REVIEW

**Comment by huayunh** [comment]
@daileytj have you seen this before? The project builds fine locally.

```
TypeError: Cannot read property 'scale' of null

       95 |                 document.getElementById('fireworks') || document.createElement('div');
       96 |             fireworksContainer.innerHTML = '';
    >  97 |             const fireworks = new FireworksCanvas(fireworksContainer, {
          |                               ^
       98 |                 maxRockets: 3,
       99 |                 rocketSpawnInterval: 600,
      100 |                 numParticles: 150,
```

**Comment by daileytj** [comment]
> @daileytj have you seen this before? The project builds fine locally.
> 
> ```
> TypeError: Cannot read property 'scale' of null
> 
>        95 |                 document.getElementById('fireworks') || document.createElement('div');
>        96 |             fireworksContainer.innerHTML = '';
>     >  97 |             const fireworks = new FireworksCanvas(fireworksContainer, {
>           |                               ^
>        98 |                 maxRockets: 3,
>        99 |                 rocketSpawnInterval: 600,
>       100 |                 numParticles: 150,
> ```

Haven't seen this before. I'll take a deeper look at this.

**Comment by daileytj** [comment]
ugh... that global.scrollTo mock needs taken out

**Comment by huayunh** [comment]
just commit to my branch

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
Sorry that took so long. Should be good to go.

**Pull request merged**
