### PR TITLE
Release R19

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Release all of the latest goodies for R19

### CODE REVIEW

**Comment by huayunh** [comment]
Asking Mariana for permission to get listed & get a photo of hers.

**Comment by huayunh** [comment]
Still any chance for an April Fool's Day theme? 😛

**Comment by joebochill** [comment]
> Still any chance for an April Fool's Day theme? 😛

If you're messing with photos, can you update our team photos to be something like 80x80 instead of 40x40? They're blurry on the Our Team page.

**Review by huayunh — APPROVED** [review]
Let's go!

**Review by emclaug2 — APPROVED** [review]
Press. That. Button!

**Pull request merged**
