### PR TITLE
Embed PXB CLI Tutorial

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Embedded the CLI tutorial to http://localhost:3000/development/cli
- Componentized the embedding for future use

#### Screenshots:
image

### CODE REVIEW

**Review by joebochill — APPROVED** [review]
Looks good to me. How does it look on mobile? 

You may want to move the embeddedplayer component into another folder. The `components/resources` folder right now only contains components used on the Resources page.

**Review by daileytj — APPROVED** [review]
Looks good to me. Next time we do a video we'll have to make sure text is a little larger in the terminal and code windows.

**Comment by huayunh** [comment]
> Looks good to me. How does it look on mobile? 

Totally responsive. Resize with the page body width

**Comment by jeffvg** [comment]
verifying this on my PC. We have a lot of blocking going on.
Blocking
Enhanced Tracking Protection
This URL matches a known tracker and it would be blocked with Content Blocking enabled.

**Comment by jeffvg** [comment]
> Corporation PC's are blocking items on tracking but video seem ok.
> 
> image

Nothing we can do with the tracking items for eaton pc users. Everything seems fine now but if pc policies change up we might have blocked video

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
