### PR TITLE
Add ability to deep link to search results

### LINKED ISSUE #190: deeplink into a search result
-- https://github.com/pxblue/doc-it/pull/188#pullrequestreview-422624825

So maybe we can use pxblue.github.io/page-name?q=mysearchterm to deep-link to a certain search result on any given page. 

#### Describe the current behavior

It doesn't in #188.

#### Is this request related to a current issue?

This feature request is valid after #188 is merged

### PR DESCRIPTION
**Pull request by joebochill**
Fixes #190.

Changes proposed in this Pull Request:
- Parse URL to deep link into search `.....?search=<searchquery>`
- Handle loading results based strictly on the URL
- Ability to go forward and back (browser) through search results correctly

### CODE REVIEW

**Comment by jeffvg** [comment]
Search failing for me.

Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by huayunh** [comment]
Get the same console warning on change

**Comment by joebochill** [comment]
Wow, I got so caught up in getting the deep linking search working that I didn't realize I broke the actual input field 🤦 
Should be working as expected now.

**Comment by joebochill** [comment]
Doc-It link checker keeps throwing 429 errors on github links (Too many Requests). It's happened sporadically in the past, but seems to be more frequent lately. Something to keep an eye on.

**Pull request merged**
