### PR TITLE
Update all body1/600 to say Subtitle 1

### PR DESCRIPTION
**Pull request by huayunh**
For PXBLUE-XXX

#### Changes proposed in this Pull Request:
- Make all body1 instances to say subtitle 1
- The table on the typography page is now programmatically generated

#### Screenshots:
image

### CODE REVIEW

**Comment by huayunh** [comment]
Hmm, don't know where to find another copy of that besides this:
https://web.archive.org/web/20200215051934/https://designguidelines.withgoogle.com/ads-branding/assets/1hquKP2EcBlDaWyaLkoezqd8r9KPjRgnp/visual-guidelines-google-marketing-platform.pdf

**Comment by joebochill** [comment]
Google Fiber has some illustration guidelines: https://fiber-brand.appspot.com/illustration

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
Nice job on the spec image cleanup.

**Comment by huayunh** [comment]
I used the Wayback machine one in the commit above since it appears to be more comprehensive

**Comment by joebochill** [comment]
When I open that link, this is what I see:
image

**Comment by huayunh** [comment]
image

**Comment by joebochill** [comment]
image

**Comment by huayunh** [comment]
hmMmmmmMm ok... strange

Yeah let me see how to incorporate that fiber link

**Pull request merged**
