### PR TITLE
Feature/mbela docit images

### PR DESCRIPTION
**Pull request by mvbela**
For PXBLUE-2360

#### Changes proposed in this Pull Request:
- Update doc-it images

### CODE REVIEW

**Comment by huayunh** [comment]
Hi Mariana!

**Comment by joebochill** [comment]
Since this is a draft, are we planning to make more changes or is this open for commentary?

**Comment by huayunh** [comment]
More changes coming, but feel free to comment

**Comment by huayunh** [comment]
Why do these look so different from the original? The map is merging into the background
image

**Comment by mvbela** [comment]
Hi @huayunh,
Yes, I had to recreate the images, since I couldn't find the original ones. Remember we talked about it and we discussed that as long as the idea/topic of the text in doc-it still applies to the image it's fine.. but I can redesign them to be as close as posible - sorry if I misinterpreted!
The other one you might notice is too different is the animation one, from Style Guide > Illustrations. I couldn't find the original animation.

**Comment by huayunh** [comment]
> /patterns/navigation, the top-left corner of this drawer is a PX Blue logo... 

This is not changed?

**Comment by huayunh** [comment]
Next time when you feel like something should have been made ready for you but it isn't, just ask, and I would have send you [a link](https://www.figma.com/file/Va1u8iMNuy8CJ7Lq44Lzbc/Project-Identity?node-id=0%3A1)...

**Comment by huayunh** [comment]
> /patterns/user-auth, Joining an Organization, the checkmark color feels strange... Also, can you change the pxb logo on this screen to be something that looks more like a logo? Can be any material design icons, and make it more colorful & stylized

This is not addressed

**Comment by huayunh** [comment]
image
why is the status bar blue

**Comment by huayunh** [comment]
what's changed in src/app/assets/design-patterns/lists/notification-buckets-1.png ?

**Comment by huayunh** [comment]
src/app/assets/design-patterns/loading-states/overlay-spinner.png src/app/assets/design-patterns/navigation/collapsible.png src/app/assets/design-patterns/navigation/content-cover-tablet.png still have Eaton

**Comment by huayunh** [comment]
I did not check all of them; can you double-check first? You can compare the diff here: 
image

**Comment by emclaug2** [comment]
This looks fantastic @mvbela

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
