### PR TITLE
Add types package and use PXBlueColor

### PR DESCRIPTION
**Pull request by emclaug2**
Changes proposed in this Pull Request:
- Use the Types package.

Whenever new versions of the Color package are released, the @pxblue/types package might be removed.

### CODE REVIEW

**Comment by huayunh** [comment]
Should we list the type package under `doc-it/src/__configuration__/resources`? Or is it too confusing for the PXBlue users?

**Comment by joebochill** [comment]
> Should we list the type package under `doc-it/src/__configuration__/resources`? Or is it too confusing for the PXBlue users?

I would say probably no. Nobody is expected to use the package directly (it's just a dependency of the colors package).

**Comment by joebochill** [comment]
@emclaug2 if you confirm that the beta version of the colors package works as expected i'll publish a latest and we can update that instead of having a direct dependency on the types package.

**Comment by emclaug2** [comment]
@joebochill  The beta version of the @pxblue/colors package currently lists the @pxblue/types package as a transitive dependency.  If someone uses either the @pxblue/colors or @pxblue/colors-branding package, they will have access to the @pxblue/types package as well.  

I tested this in both JS and TS projects with no complications.  

I would not merge this PR yet; doc-it shoud not need need to explicitly list the @pxblue/types package.

**Pull request merged**
