### PR TITLE
Add Earth Day theme

### PR DESCRIPTION
**Pull request by huayunh**
Fixes PXBLUE-some-earth-day-theme-story

Appbar icons come from https://thenounproject.com/kerismaker/collection/mother-earth-day-glyph/ by tezar tantular under CC-BY. Need to add this to a credits page in the future.

#### Screenshots:
image

### CODE REVIEW

**Review by daileytj — APPROVED** [review]
Looks good. Love the rotating earth piece in there. Can you add the attributions as a comment to the attributions page story in jira so we don't lose it?

**Comment by daileytj** [comment]
Never mind on the updating the attributions story... I just added it.

**Comment by joebochill** [comment]
I would like to see the attributions page in place before we start using more icons from noun project. Even if it’s something super basic for now.

**Comment by jeffvg** [comment]
looks nice! I like. Do we merge this for now and catch-up with attributions page later?

**Review by jeffvg — APPROVED** [review]

**Comment by daileytj** [comment]
> I would like to see the attributions page in place before we start using more icons from noun project. Even if it’s something super basic for now.

https://github.com/pxblue/doc-it/pull/385

**Pull request merged**
